title:        Road Map
url:          http://road-map.apievangelist.com

logo:         https://s3.amazonaws.com/kinlane-productions/api-evangelist/api-evangelist-roadmap.png
logo_width:   80
logo_bottom_padding: 10

version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     kramdown

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 150
paginate_path: "/news/page:num"

categories_path : /categories.html
tags_path : /tags.html

org: api-evangelist
repo: road-map
resource: road-map
oauthio: qUDL4eZqKPFb41SwuWIYIwLR6jI

get_color: 009900
post_color: 0000ff
put_color: FF0080
delete_color: FF9900

# Masthead title
masthead_link: http://road-map.apievangelist.com
masthead_font_size: 80
masthead_title: '{"Road Map"}'

# Feature
feature_title: API Design Providers Guide
feature_link: http://apis.how/xzca4kr2wb
feature_image_source: https://s3.amazonaws.com/kinlane-productions/whitepapers/3scale/report-image-api-design.png
feature_image_width: 45

# Project
project_image: http://kinlane-productions.s3.amazonaws.com/api-evangelist-site/building-blocks/bw-highway.png
project_summary: This is a project to keep track on how companies are publishing road maps around the operations of APIs. I'm looking to understand how they do it, and apply to my own APIs, while also sharing the approach with others along the way.

# Navigation
navigation:
  - label1: Home
    link1: /index.html
    size1: 80
    extend: 0
    label2:
    link2:
    size2: 0
    padding: 0
    decorate: 0
  - label1: News
    link1: /news/
    size1: 80
    extend: 1
    label2: RSS
    link2: /blog.xml
    size2: 60
    padding: 5
    decorate: 0
  - label1: API
    link1: /api/
    size1: 80
    extend: 1
    label2: JSON
    link2: apis.json
    size2: 60
    padding: 5
    decorate: 0
  - label1: Organizations
    link1: /organizations/
    size1: 80
    extend: 1
    label2: JSON
    link2: /data/organizations.json
    size2: 60
    padding: 0
    decorate: 0
  - label1: Building Blocks
    link1: /building-blocks/
    size1: 80
    extend: 1
    label2: JSON
    link2: /data/buildingblocks.json
    size2: 60
    padding: 0
    decorate: 0
  - label1: Return to API Evangelist
    link1: http://apievangelist.com
    size1: 80
    extend: 0
    label2:
    link2:
    size2: 10
    padding: 12
    decorate: 1

# Footer Navigation
footernavigation:
  - label: API 100K View
    link: http://apievangelist.com
  - label: News
    link: /news/
  - label: Partners
    link: http://apievangelist.com/partners/
  - label: APIs.json
    link: http://apisjson.org
  - label: About Kin Lane
    link: http://kinlane.com
  - label: Branding Guidelines
    link: http://apievangelist.com/branding-guidelines.html
  - label: Contact
    link: http://kinlane.com/contacts/

# sponsors
sponsors_margin_top: 15
sponsors_padding_top: 3
sponsors_json_url: https://s3.amazonaws.com/kinlane-productions/json/sponsors.json
